### ISSUE TITLE
Reproducibility Hackathon, Ciera Martinez, 2015-01-14, 2PM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#1]
- Guest speaker: Ciera Martinez
- Date: 2015-01-14
- Time: 2 pm PST ([everytimezone link](http://everytimezone.com/#2015-1-14,600,cn3))
- Length: 1 hr
- **Collaborative notes:** Etherpad: ~~https://ropensci.etherpad.mozilla.org/comm-call-0114~~ updated link: https://public.etherpad-mozilla.org/p/ropensci.comm-call-0114 (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/) - we have this service through UC Berkeley
  - Up to 100 people in the call, this should be sufficient
  - Link to meeting: https://bluejeans.com/122792299/5433
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - NESCENT rrhack - Ciera Martinez - Ciera will present highlights from the rrhack event.
  - Recent rOpenSci developments - We'll go over notable developments in rOpenSci software and community.
  - rOpenSci hackathon in San Francisco - We'll be having our 2nd annual US unconference at GitHub HQ.
  - Q/A session - This will be an open Q/A session, where anyone can ask about all things rOpenSci, either on software, community, etc.

**Comment by kcranston** [comment]
Links for the rrhack parts:
* [rrhack on github](https://github.com/Reproducible-Science-Curriculum) - includes proposed lessons
* [hackathon repo](https://github.com/Reproducible-Science-Curriculum/Reproducible-Science-Hackathon-Dec-08-2014) - info from the hackathon

**Comment by sckott** [comment]
Notes on the meeting: 

* You don't have to call in, you can just join in on the etherpad if you want. For best results though, doing both is best.
* If you join the call, there are various ways you can join: via your browser, or call in via phone, or use a smartphone bluejeans app. 
* On the call, you will be automatically muted on entry. You can unmute yourself if you need to talk. 
* There is video on the call, which we'll use to allow any screen sharing. 
* There is a chat client in both the Etherpad and the BlueJeans call app - let's stick to using chat in Etherpad

**Comment by karthik** [comment]
Can we switch the order so the rrhack update is first, then rOpenSci updates, finishing with unconf?

**Comment by sckott** [comment]
sure, sounds good

**Comment by sckott** [comment]
__Post call content__

* Video of the call: https://vimeo.com/116918865
* Collaborative notes: https://ropensci.etherpad.mozilla.org/comm-call-0114

**Comment by sckott** [comment]
__NOTE__: All our etherpads were lost due to Mozilla killing the service with no notice - we'll retrieve them as soon as possible and put up somewhere else
