### ISSUE TITLE
Python String Methods in R, pystr - Nicole White; 2016-05-11, 9AM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#10]
- Guest speakers: [Nicole White](https://github.com/nicolewhite)
- Date: 2016-05-11
- Time: 9 am PST ([everytimezone link](http://everytimezone.com/#2016-5-11,240,cn3))
- Length: 1 hr
- **Collaborative notes:** https://docs.google.com/document/d/1HiE-6JCrH3NahTWeZVAQhuahSfJkJ6HuMqIdMQPm9d4/edit# (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/) - You can get desktop native apps for all major platforms or browser extension at [http://bluejeans.com/downloads](http://bluejeans.com/downloads)
  - BlueJeans didn't work on Chrome for a while, should work now - should also work on Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/623151186 
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Nicole White on [pystr](https://github.com/nicolewhite/pystr)
  - Q/A session

**Comment by soodoku** [comment]
Link to speaker name goes to @jennybc 
Is it meant to?

**Comment by sckott** [comment]
fixed now

**Comment by tierneyn** [comment]
Keen to join! But I think I'll have to skip this one; 9am = 2am down under. Next time!

**Comment by jennybc** [comment]
I am probably also unable to attend this one 😞.

**Comment by sckott** [comment]
__Post call content__

* Video: Coming soon...
* Notes: https://docs.google.com/document/d/1HiE-6JCrH3NahTWeZVAQhuahSfJkJ6HuMqIdMQPm9d4/edit# 
* Nicole's slides: http://nicolewhite.github.io/pystr/ropensci/#1

**Comment by jennybc** [comment]
@nicolewhite I love these slides! Sorry I missed this talk.
