### ISSUE TITLE
Advanced Graphics and Image Processing in R with magick - Jeroen Ooms; 2016-08-24, 10AM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#11]
- Guest speakers: [Jeroen Ooms](https://github.com/jeroenooms)
- Date: 2016-08-24
- Time: 10 am PST ([everytimezone link](http://everytimezone.com/#2016-8-24,300,cn3))
- Length: 1 hr
- **Collaborative notes:** https://docs.google.com/document/d/1BDFZZpPhCKy7VmzZK8oW1lKbnqOMK0Sdoid9TZJpvss/edit (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/) - You can get desktop native apps for all major platforms or browser extension at [http://bluejeans.com/downloads](http://bluejeans.com/downloads)
  - BlueJeans didn't work on Chrome for a while, should work now - should also work on Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/233097903 
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Jeroen on [magick](https://github.com/jeroenooms/magick)
  - Q/A session

**Comment by jeroenooms** [comment]
@sckott fixed timezone link: http://everytimezone.com/#2016-8-24,300,cn3

**Comment by sckott** [comment]
thanks, fixed

**Comment by njtierney** [comment]
Alrighty, I'm gonna do my best to be here this time.

**Comment by sckott** [comment]
**Post call content**
- Video: https://vimeo.com/180799058
- Notes: https://docs.google.com/document/d/1BDFZZpPhCKy7VmzZK8oW1lKbnqOMK0Sdoid9TZJpvss/edit
