### ISSUE TITLE
How do I Create a Code of Conduct for my Event/Lab/Codebase? Pauline Barmby, Safia Abdalla, C. Titus Brown; 2016-12-15, 8AM PST 

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/commcalls#12]
- Topic: How do I create a code of conduct for my event/lab/codebase?
- Date: 2016-12-15
- Time: 8 am PST [(everytimezone link)](http://everytimezone.com/#2016-12-15,240,cn3)
- Length: 1 hr
- **Collaborative notes:** https://docs.google.com/document/d/1PZKDWaSKDoGugOIqeSnLArHFtZ4uqw5Y1rNqSzwkXnY/edit?usp=sharing (**open this link**)
- Voice/video:
  - We'll use [BlueJeans](http://bluejeans.com/) - You can get desktop native apps for all major platforms or browser extension at http://bluejeans.com/downloads
  - BlueJeans should work on Chrome/Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/917620876
  - If you call in by phone, US toll-free number is 1.888.240.2560. See [http://bluejeans.com/numbers](http://bluejeans.com/numbers) for international numbers.
- Agenda:
  - Welcome (5 min, Stefanie Butland)
  - guest: Pauline Barmby - Data/Software Carpentry’s new code of conduct (5-10 min)
  - guest: Safia Abdalla - Codes of conduct for open source: the stuff no one tells you (5-10 min)
  - guest: C. Titus Brown - How we developed our Lab Code of Conduct (5-10 min)
  - Discussion (15 min, moderated by Karthik Ram)
  - Solicit ideas for Community Calls (5 min, Stefanie)
- More [details](https://ropensci.org/blog/blog/2016/10/31/comm-call-v12), including speaker bios.

**Comment by sckott** [comment]
**Post call content**
- Video: https://vimeo.com/196503807
- Notes: https://docs.google.com/document/d/1PZKDWaSKDoGugOIqeSnLArHFtZ4uqw5Y1rNqSzwkXnY/edit?usp=sharing
