### ISSUE TITLE
rOpenSci Software Review and Onboarding, Andee Kaplan, Noam Ross; 2017-09-13, 8AM PST

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/commcalls#15]
### Join the meeting:  https://bluejeans.com/925619027
- Date: 2017-09-13
- Time: 8-9 am PT ([find your timezone](http://everytimezone.com/#2017-9-13,180,cn3))
- [Alternate connection options](https://github.com/ropensci/commcalls/blob/master/bluejeans_about.md)

### Community Call on rOpenSci Software Review and Onboarding
The objectives of this call are:
1. To share information about rOpenSci's open peer software review and onboarding process with our community of package authors and reviewers, and people who are thinking about submitting a package or reviewing for the first time
2. To get your feedback about the process and guidelines we provide
3. To answer your questions 

### Agenda:
 - Welcome (5 min, Stefanie Butland, rOpenSci Community Manager)
 - guest: Noam Ross, editor (15 min)
    - Noam will give an overview of the rOpenSci software review and onboarding, highlighting the role editors play and how decisions are made about policies and changes to the process. 
- guest: Andee Kaplan, reviewer (15 min) 
    - Andee will give her perspective as a package reviewer, sharing specifics about her workflow and her motivation for doing this. 
- Q & A (25 min, moderated by Noam Ross)

### Resources
- Video of [this Community Call](https://vimeo.com/234900351)
- [How rOpenSci uses Code Review to Promote Reproducible Science](https://www.numfocus.org/blog/how-ropensci-uses-code-review-to-promote-reproducible-science/); blog post Aug 11, 2017
- [rOpenSci Software Review: Always Improving](https://ropensci.org/blog/blog/2017/09/11/software-review-update); blog post Sep 11, 2017
- The what, why and how of [rOpenSci open peer review and onboarding](http://onboarding.ropensci.org/); guidelines
- [Software reviews](https://github.com/ropensci/onboarding/issues) in progress and completed
- [Onboarded packages](https://ropensci.org/packages/)
- Read on [our blog](https://ropensci.org/blog/) guest posts (ten since Feb 2017) by authors of onboarded packages 
- [Experiences as a first time rOpenSci package reviewer](https://ropensci.org/blog/blog/2017/09/08/first-review-experiences); guest blog post by first-time reviewer Verena Haunschmid, Sep 8, 2017
- [So you (don't) think you can review a package](https://ropensci.org/blog/blog/2017/08/22/first-package-review); guest blog post by first-time reviewer Mara Averick, Aug 22, 2017
- [Onboarding at rOpenSci: A Year in Reviews](https://ropensci.org/blog/blog/2016/03/28/software-review); blog post Mar 28, 2016

### Speaker bios
**Andee Kaplan** is a Postdoctoral Fellow at Duke University. She is a recent PhD graduate from the Iowa State University Department of Statistics, where she learned a lot about R and reproducibility by developing a class on data stewardship for Agronomists. Andee has reviewed multiple (two!) packages for rOpenSci, [`iheatmapr`](https://github.com/ropensci/onboarding/issues/107) and [`getlandsat`](https://github.com/ropensci/onboarding/issues/58), and hopes to one day be on the receiving end of the review process.

Andee on [GitHub](https://github.com/andeek), [Twitter](https://twitter.com/andeekaplan)

**Noam Ross** is one of rOpenSci's four editors for software peer review. Noam is a Senior Research Scientist at EcoHealth Alliance in New York, specializing in mathematical modeling of disease outbreaks, as well as training and standards for data science and reproducibility.  Noam earned his Ph.D. in Ecology from the University of California-Davis, where he founded the Davis R Users' Group. 

Noam on [GitHub](https://github.com/noamross), [Twitter](https://twitter.com/noamross)

### Have an idea for a Community Call? [Tell us about it](https://ropensci.org/contact.html)

**Comment by billchenxi** [comment]
Will there be new meeting?

**Comment by stefaniebutland** [comment]
Yes @billchenxi, we have Community Calls about four times a year and the next one should be in November. No date scheduled yet

**Comment by stefaniebutland** [comment]
Video of this call has been posted: https://vimeo.com/234900351
