### ISSUE TITLE
Nick Golding, rOpenSci Fellow, on zoon & greta - writing packages to support research communities; 2018-01-30, 2PM PDT

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/commcalls#16]
### Nick Golding, rOpenSci Fellow, will talk about `zoon` & `greta` - Writing Packages to Support Research Communities

I'll [Nick] be talking about two R packages I've developed recently. [zoon](https://github.com/zoonproject/zoon) aims to promote open and reproducible research in ecological modeling by helping researchers share their code in a modular way and produce reproducible research artifacts. I've recently been trying to bootstrap a community around this idea - which is a much harder problem.

[greta](https://github.com/goldingn/greta) lets you write out and fit statistical models (like Stan or BUGS) but right in R. It uses tensorflow to make models scale to massive data, and is designed to be used and extended by other modeling packages. greta relies on some nice R tricks and lots of thinking about designing APIs for both users and developers.

### Bio
**Nick Golding** is an applied computational statistician working as a Research Fellow in the [Quantitative & Applied Ecology Group](https://qaeco.com/) at the University of Melbourne, Australia. He develops statistical models and software to predict the distributions of species and human diseases like those caused by the Zika and Ebola viruses. He is particularly interested in improving these models with information about traits, mechanistic relationships and population dynamics. [Nick received an rOpenSci Fellowship](https://ropensci.org/blog/2016/12/12/ropensci-fellowship-zoon/) to continue developing a framework for building and sharing reproducible species distribution models. 

Nick on [GitHub](https://github.com/goldingn), [Twitter](https://twitter.com/_nickgolding_), [Google Scholar](https://scholar.google.co.uk/citations?user=peoal7wAAAAJ&hl)

### When
- Date: 2018-01-30 in Berkeley, CA; 2018-01-31 in Melbourne, AU
- Time: 2-3pm PST ([find your timezone](http://bit.ly/2BwjnZM))

### Join the meeting  
- Join from PC, Mac, Linux, iOS or Android: https://berkeley.zoom.us/j/121119633 (requires app installation first time)
- Or iPhone one-tap: 
  - US: +16699006833,,121119633# or +16465588656,,121119633# 
- Or Telephone: 
  - Dial (for higher quality, dial a number based on your current location): US: +1 669 900 6833 or +1 646 558 8656 or +1 877 853 5247 (Toll Free) or +1 877 369 0926 (Toll Free)
  - Meeting ID: 121 119 633 
  - International numbers available: https://berkeley.zoom.us/zoomconference?m=7olOpvCUQY1fM4tneVnitp-BZB7wiBc_  

### Agenda
- Welcome (5 min, Stefanie Butland, rOpenSci Community Manager)
- guest: Nick golding (35 min)
- Q & A (20 min, moderated by Scott Chamberlain)

### Resources
- Collaborative notes [google doc](http://bit.ly/2EEhsnr)
- [Announcing our first fellowship awarded to Dr. Nick Golding](https://ropensci.org/blog/2016/12/12/ropensci-fellowship-zoon/); blog post Dec 12, 2016
- Zoon publication: Nick Golding, Tom August, Tim Lucas, David Gavaghan, E. Emiel van Loon, Greg McInerny (2017). The zoon r package for reproducible and shareable species distribution modeling. Methods Ecol Evol https://doi.org/10.1111/2041-210X.12858
- Soon after the Community Call, we'll post the [video](https://vimeo.com/channels/rocommunitycalls)

**Comment by vrra** [comment]
how can i add this to my (google) calendar? is there an ics file somewhere?

**Comment by stefaniebutland** [comment]
@vrra Here's a link to rOpenSci's public Google Calendar: http://bit.ly/2ETzyAS. 

Let me know if it doesn't work to add to yours
