### ISSUE TITLE
htmlwidgets - Binding JS Libraries Made Easy, Ramnath Vaidyanathan, 2015-03-05, 2PM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#2]
- Guest speaker: [Ramnath Vaidyanathan](http://ramnathv.github.io/)
- Date: 2015-03-05
- Time: 2 pm PST ([everytimezone link](http://everytimezone.com/#2015-3-5,600,cn3))
- Length: 1 hr
- **Collaborative notes:** Etherpad: ~~https://ropensci.etherpad.mozilla.org/comm-call-0305~~ updated link: https://public.etherpad-mozilla.org/p/ropensci.comm-call-0305 (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/) - we have this service through UC Berkeley
  - Up to 100 people in the call, this should be sufficient
  - Link to meeting: https://bluejeans.com/944674810
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Ramnath Vaidyanathan - Ramnath will demo [htmlwidgets](http://www.htmlwidgets.org/), an R package that makes it easy to create bindings to javascript visualization libraries.
  - Recent rOpenSci developments - We'll go over notable developments in rOpenSci software and community.
  - Q/A session - An open Q/A session - Ask about all things rOpenSci, on software, community, etc.

**Comment by karthik** [comment]
Questions to Ramnath or us are welcome here ahead of time.

**Comment by sckott** [comment]
__Post call content__

* Video: https://vimeo.com/XXXXXXXX
* Notes: https://ropensci.etherpad.mozilla.org/comm-call-0305

**Comment by sckott** [comment]
__NOTE__: All our etherpads were lost due to Mozilla killing the service with no notice - we'll retrieve them as soon as possible and put up somewhere else
