### ISSUE TITLE
Getting Your Data into R, Hadley Wickham, 2015-04-15, 2PM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#3]
- Guest speaker: [Hadley Wickham](http://hadley.com/)
- Date: 2015-04-15
- Time: 2 pm PST ([everytimezone link](http://everytimezone.com/#2015-4-15,540,cn3))
- Length: 1 hr
- **Collaborative notes:** Etherpad: ~~https://ropensci.etherpad.mozilla.org/comm-call-04-15~~ updated link: https://public.etherpad-mozilla.org/p/ropensci.comm-call-04-15 (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/)
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/383477126
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Hadley Wickham (http://had.co.nz/) - Hadley will go over data ingest in R, covering some new packages he's working on
  - Q/A session - An open Q/A session - Ask about Hadley's talk

**Comment by karthik** [comment]
Hadley has confirmed that he can speak on the 15th. He'll do a little demo on data ingest and
then open it for questions.

**Comment by karthik** [comment]
PS: For anyone planning to attend, questions are also welcome here ahead of time.

**Comment by llattes** [comment]
Hi @sckott, @karthik! Are the recordings of this call already available? I attended the meeting for 15 minutes but unfortunately had to leave due to other appointments. Thanks in advance!

**Comment by sckott** [comment]
@llattes yes, it will be up today probably on our Vimeo channel https://vimeo.com/ropensci

**Comment by sckott** [comment]
__Post call content__

* Video: https://vimeo.com/125174198
* Notes: https://ropensci.etherpad.mozilla.org/comm-call-04-15

**Comment by sckott** [comment]
__NOTE__: All our etherpads were lost due to Mozilla killing the service with no notice - we'll retrieve them as soon as possible and put up somewhere else
