### ISSUE TITLE
Getting NCBI Data into your R Sessions, rentrez - David Winter; rocker, Docker for R - Carl Boettiger; 2015-05-27, 2PM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#4]
- Guest speakers: [David Winter](http://theatavism.blogspot.com/), [Carl Boettiger](http://www.carlboettiger.info/)
- Date: 2015-05-27
- Time: 2 pm PST ([everytimezone link](http://everytimezone.com/#2015-5-27,540,cn3))
- Length: 1 hr
- **Collaborative notes:** Etherpad: ~~https://ropensci.etherpad.mozilla.org/comm-call-05-27~~ updated link: https://public.etherpad-mozilla.org/p/ropensci.comm-call-05-27 (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/)
  - BlueJeans no longer works on Chrome - Use Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/110125479
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda:  We'll do a series of smaller lightning talks this time
  - David Winter on [rentrez](https://github.com/ropensci/rentrez)
  - Carl Boettiger on [Rocker](https://registry.hub.docker.com/repos/rocker/) ([github org](https://github.com/rocker-org))
  - Q/A session - An open Q/A session

**Comment by sckott** [comment]
questions for the speakers or for us are welcome here prior to the presentation - or put quesitons in the etherpad link above

**Comment by benmarwick** [comment]
I'd like to hear more about Rich's [remake package](https://github.com/richfitz/remake/), which I saw a brief but very impressive demo of at the unconf...

**Comment by sckott** [comment]
@richfitz there's a request for remake

**Comment by karthik** [comment]
We should also include a quick intro to the tool and speaker bios where possible.

**Comment by sckott** [comment]
intro to what tool? speaker bios?

**Comment by karthik** [comment]
Yeah, for those that wont know who Rich/David are. People like Hadley need no intro but most of our other speakers will.

**Comment by sckott** [comment]
right, sounds good

**Comment by KnowledgeGarden** [comment]
Planning to attend May 27. Most interested in rentrez; I hacked my own utilities for pubmed; will start looking at rentrez

**Comment by sckott** [comment]
great, see you then @KnowledgeGarden - Questions to David, Carl, or us are welcome here ahead of time.

**Comment by dwinter** [comment]
Hi @KnowledgeGarden -- one of my goals with rentrez it to make it was for developers to build off it (i.e. rentrez wraps the API, plays nice with usage policy and get's you sensible R objects, meaning devs can worry about the Cool Stuff they want to do not how to build a request).

Would be keen to know if rentrez works in that role, or answer any Q's you have about it

**Comment by KnowledgeGarden** [comment]
Using R objects represents an addition to my existing work; it takes time to build up interfaces. I will keep you in the loop.

**Comment by dwinter** [comment]
Couple of links to include in the ether-pad 

* slides: http://dwinter.github.io/ropensci-comcall/
* example from which my demo is adapted: https://gist.github.com/dwinter/8b98bf57a287ac9f389a
* rensembl which I'm going to ask for help on https://github.com/dwinter/rensembl

**Comment by sckott** [comment]
__Post call content__

* Video: XXXXXX
* Notes: https://ropensci.etherpad.mozilla.org/comm-call-05-27

**Comment by sckott** [comment]
__NOTE__: All our etherpads were lost due to Mozilla killing the service with no notice - we'll retrieve them as soon as possible and put up somewhere else
