### ISSUE TITLE
Tools for R package development, metacran - Gábor Csárdi; 2015-08-19, 9 AM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#6]
- Guest speakers: [Gábor Csárdi](http://gaborcsardi.org/)
- Date: 2015-08-19
- Time: 9 am PST ([everytimezone link](http://everytimezone.com/#2015-8-19,240,cn3))
- Length: 1 hr
- **Collaborative notes:** Etherpad: ~~https://ropensci.etherpad.mozilla.org/comm-call-08-19~~ updated link: https://public.etherpad-mozilla.org/p/ropensci.comm-call-08-19 (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/)
  - BlueJeans no longer works on Chrome - Use Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/562095325
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Gabor on [metacran](http://www.r-pkg.org/) [on github](https://github.com/metacran)
  - Scott w/ brief [fulltext](https://github.com/ropensci/fulltext) demo 
  - Carl w/ brief chat about [packages.ropensci.org](https://packages.ropensci.org)
  - Q/A session - An open Q/A session

**Comment by gaborcsardi** [comment]
Thanks to ROpenSci for inviting me as a guest!

I'll show a lot of R tools I have been involved with as a developer, many of them related to metacran, others not. Some are mature, some barely more than ideas.  The common theme is _creating tools for R package development_. I strongly believe that everybody who writes R code is also an R package developer, or will be soon.

Here is the list of tools. I probably won't have time to show all of them, so if you want to hear about or discuss a particular tool, please let me know here or privately, and then I'll definitely include it.

* http://www.r-pkg.org web site to search, browse and discover R packages
* [crandb](https://github.com/metacran/crandb), database of CRAN packages
* cranlogs [db](https://github.com/metacran/cranlogs.app) and
  [R package](http://www.r-pkg.org/pkg/cranlogs)
* CRAN-related badges, do we want badges for CRAN checks?
* CRAN @ GitHub mirror
* [r-builder](https://github.com/metacran/r-builder): CI with multiple versions of R
* [r-hub proposal](https://github.com/r-hub/proposal): an everything-builder proposal
  for the R consortium
* future plans for metacran
* [collection of R idioms](https://github.com/gaborcsardi/idioms)
* tools towards a nicer command line interface
  ([keypress](http://www.r-pkg.org/pkg/keypress),
   [ask](https://github.com/gaborcsardi/ask),
   [crayon](http://www.r-pkg.org/pkg/crayon),
   [progress](http://www.r-pkg.org/pkg/progress), etc.)
* [mason](https://github.com/metacran/mason) to quickly build full fledged R packages
* [pkgconfig](http://www.r-pkg.org/pkg/pkgconfig) package options that do
  not mess with other packages using the same package
* [maxygen](https://github.com/gaborcsardi/maxygen): write R docs in Markdown
* [argufy](https://github.com/gaborcsardi/argufy): declerative function argument checks

**Comment by sckott** [comment]
@gaborcsardi put a link in for your slides when you get a chance

**Comment by gaborcsardi** [comment]
Link to slides: https://github.com/metacran/ropensci-commcall-2015

Thanks everyone for attending!

**Comment by jennybc** [comment]
Thanks @gaborcsardi for all of the above work and the talk. I normally attend these but was still on a camping trip yesterday. Belated regrets.

**Comment by sckott** [comment]
__Post call content__

* Video: https://vimeo.com/140267425
* Notes: https://ropensci.etherpad.mozilla.org/comm-call-08-19

**Comment by sckott** [comment]
__NOTE__: All our etherpads were lost due to Mozilla killing the service with no notice - we'll retrieve them as soon as possible and put up somewhere else
