### ISSUE TITLE
Failing Fast and Early, assertr - Tony Fischetti; 2015-10-07, 9AM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#7]
- Guest speakers: [Tony Fischetti](http://www.onthelambda.com/)
- Date: 2015-10-07
- Time: 9 am PST ([everytimezone link](http://everytimezone.com/#2015-10-07,240,cn3))
- Length: 1 hr
- **Collaborative notes:** Google docs: https://docs.google.com/document/d/1qvJmMCw-TFsq70r6Qb19SVbhr24PsbrSV5zHdRLz7Cc/edit?usp=sharing (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/)
  - BlueJeans no longer works on Chrome - Use Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/109742055
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Tony Fischetti on [assertr](https://github.com/tonyfischetti/assertr)
  - Q/A session

**Comment by sckott** [comment]
__UPDATE__: Mozilla deleted all our etherpads, including the one we set up for this call. We're working on a new solution...and will put up new link when we have it

**Comment by sckott** [comment]
__UPDATE__: link updated

**Comment by richfitz** [comment]
Wikipedia also has etherpads: https://etherpad.wikimedia.org/ - might be worth trying too?

**Comment by sckott** [comment]
@richfitz  perhaps, is that maintained by wikipedia? (ie.. on their servers)

**Comment by tonyfischetti** [comment]
Thanks everyone! If you think of any more questions, hit me up.
As far `assertr`'s future home, I think @karthik said that it'll move ROpenSci's repo very soon.

**Comment by sckott** [comment]
__Post call content__

* Video: https://vimeo.com/141906295
* Notes: https://docs.google.com/document/d/1qvJmMCw-TFsq70r6Qb19SVbhr24PsbrSV5zHdRLz7Cc/edit?usp=sharing
