### ISSUE TITLE
Designing dat 1.0 - Karissa McKelvey; 2015-12-02, 9AM PST

### ISSUE THREAD

**Issue by sckott** [ropensci/commcalls#8]
- Guest speakers: [Karissa McKelvey](http://karissa.github.io/)
- Date: 2015-12-02
- Time: 9 am PST ([everytimezone link](http://everytimezone.com/#2015-12-2,300,cn3))
- Length: 1 hr
- **Collaborative notes:** https://docs.google.com/document/d/14RMFe1iFsIOvBNxxE45Vn2eFRpXMRwQ3sbztUh7-72c/edit?usp=sharing (**open this link**)
- Voice/video: 
  - We'll use [BlueJeans](http://bluejeans.com/)
  - BlueJeans didn't work on Chrome for a while, should work now - should also work on Firefox/Safari
  - Up to 100 people in the call
  - Link to meeting: https://bluejeans.com/614356166
  - If you call in, there is a US number and US toll free number. See http://bluejeans.com/numbers for international numbers
- Agenda: 
  - Karissa McKelvey on [dat](http://dat-data.com/)
  - Q/A session

**Comment by karthik** [comment]
Our speaker will be the awesome @karissa speaking about Dat!

**Comment by gaborcsardi** [comment]
Very cool!

**Comment by sckott** [comment]
:rocket:

**Comment by karissa** [comment]
Woo hoo, very excited to be able to chat about dat!

**Comment by sckott** [comment]
@karissa Can you call in about 5 min early so we can make sure video/audio/screen sharing is working?  Any questions let us know.

**Comment by karissa** [comment]
@sckott  Got it!

**Comment by sckott** [comment]
__Post call content__

* Video: https://vimeo.com/147914258
* Notes: https://docs.google.com/document/d/14RMFe1iFsIOvBNxxE45Vn2eFRpXMRwQ3sbztUh7-72c/edit?usp=sharing
